# Generated by Django 3.2.5 on 2021-09-29 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='ordered',
        ),
        migrations.AddField(
            model_name='billitem',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='company.project'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='site_er',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='company.siteer'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='state',
            field=models.CharField(choices=[('E', 'Editing'), ('P', 'Request Placed'), ('O', 'Order placed'), ('D', 'Delivered')], default='E', max_length=1),
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
