# Generated by Django 3.2.7 on 2021-09-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210929_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pending_request',
            field=models.IntegerField(default=0),
        ),
    ]
