# Generated by Django 3.2.7 on 2021-09-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_project_pending_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='state',
            field=models.CharField(choices=[('E', 'Editing'), ('P', 'Request Placed'), ('O', 'Order placed'), ('A', 'Order Accepted'), ('D', 'Delivered'), ('V', 'Delivery Verified'), ('R', 'Rejected')], default='E', max_length=1),
        ),
    ]
